### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pacahon** [cscenter/site-frontend#119]
- [ ] Обдумать `title-label survey-label`. Как-то там стрёмно всё сейчас выглядит, изучить решение в semantic-ui.
- [x]  Проверить, используется ли `form_title`. Кажется, что осталось в css только. Удалить, если это так.
- [ ] Разобраться с `_card__img`. Чот странное творится.
- [ ] `cover__btns` нужно сделать универсальным решением. Переименовать.
